--[[
**********************************************************************
*
* FILEHEADER: Elboydo's Armed Vehicles Framework (AVF) AI V3 - The Racing Edition 
*
* FILENAME :        names.lua             
*
* DESCRIPTION :
*       File that contains all racer names (and unique names) 
*		

*
* NOTES :
*       
*
* AUTHOR :    elboydo        START DATE   :    Jan  2021
* 							 Release Date :    29 Nov 2021 
*
]]

fNames = {
		[1] = "Lewis",
		[2] = "Jack",
		[3] = "Ryan",
		[4] = "James",
		[5] = "Callum",
		[6] = "Cameron",
		[7] = "Daniel",
		[8] = "Liam",
		[9] = "Jamie",
		[10] = "Kyle",
		[11] = "Matthew",
		[12] = "Logan",
		[13] = "Finlay",
		[14] = "Adam",
		[15] = "Alexander",
		[16] = "Dylan",
		[17] = "Aiden",
		[18] = "Andrew",
		[19] = "Ben",
		[20] = "Aaron",
		[21] = "Connor",
		[22] = "Thomas",
		[23] = "Joshua",
		[24] = "David",
		[25] = "Ross",
		[26] = "Luke",
		[27] = "Nathan",
		[28] = "Charlie",
		[29] = "Ethan",
		[30] = "Aidan",
		[31] = "Michael",
		[32] = "John",
		[33] = "Calum",
		[34] = "Scott",
		[35] = "Josh",
		[36] = "Samuel",
		[37] = "Kieran",
		[38] = "Fraser",
		[39] = "William",
		[40] = "Oliver",
		[41] = "Rhys",
		[42] = "Sean",
		[43] = "Harry",
		[44] = "Owen",
		[45] = "Sam",
		[46] = "Christopher",
		[47] = "Euan",
		[48] = "Robert",
		[49] = "Kai",
		[50] = "Jay",
		[51] = "Jake",
		[52] = "Lucas",
		[53] = "Jayden",
		[54] = "Tyler",
		[55] = "Rory",
		[56] = "Reece",
		[57] = "Robbie",
		[58] = "Joseph",
		[59] = "Max",
		[60] = "Benjamin",
		[61] = "Ewan",
		[62] = "Archie",
		[63] = "Evan",
		[64] = "Leo",
		[65] = "Taylor",
		[66] = "Alfie",
		[67] = "Blair",
		[68] = "Arran",
		[69] = "Leon",
		[70] = "Angus",
		[71] = "Craig",
		[72] = "Murray",
		[73] = "Declan",
		[74] = "Zak",
		[75] = "Brandon",
		[76] = "Harris",
		[77] = "Finn",
		[78] = "Lee",
		[79] = "Lennon",
		[80] = "Cole",
		[81] = "George",
		[82] = "Jacob",
		[83] = "Mark",
		[84] = "Hayden",
		[85] = "Kenzie",
		[86] = "Alex",
		[87] = "Shaun",
		[88] = "Louis",
		[89] = "Caleb",
		[90] = "Mason",
		[91] = "Gregor",
		[92] = "Mohammed",
		[93] = "Luca",
		[94] = "Harrison",
		[95] = "Kian",
		[96] = "Noah",
		[97] = "Paul",
		[98] = "Riley",
		[99] = "Stuart",
		[100] = "Joe",
		[101] = "Jonathan",
		[102] = "Stephen",

}


sNames = {
[1] = "Smith",
[2] = "Brown",
[3] = "Wilson",
[4] = "Stewart",
[5] = "Thomson",
[6] = "Robertson",
[7] = "Campbell",
[8] = "Anderson",
[9] = "Murray",
[10] = "Macdonald",
[11] = "Taylor",
[12] = "Scott",
[13] = "Reid",
[14] = "Clark",
[15] = "Hamilton",
[16] = "Morrison",
[17] = "Walker",
[18] = "Ross",
[19] = "Watson",
[20] = "Graham",
[21] = "Fraser",
[22] = "Young",
[23] = "Hill",
[24] = "Simpson",
[25] = "Hunter",
[26] = "Ferguson",
[27] = "Douglas",
[28] = "King",
[29] = "Findlay",
[30] = "Jamieson",
[31] = "Macleod",
[32] = "White Cresta",
[33] = "Burns",
[34] = "Kennedy",
[35] = "Mckenzie",
[36] = "Sutherland",
[37] = "Wood",
[38] = "Hughes",
[39] = "Mcmillan",
[40] = "Cunningham",
[41] = "Boyle",
[42] = "Gibson",
[43] = "Gibson",
}




uniqueNames = {
	[1] = 	"Dennis Gustafsson",
	[2] =  	"Resident Emil",
	[3] =	"Gordon Woo",
	[4] =	"Lawrence Lee Jr.",
	[5] =	"Gillian Johnson",
	[6] =	"Tracy",
	[7] =	"Parisa Terdiman",
	[8] = "Elboydo",
	[9] = "Spexta",
	[10] = "Dima",
	[11] = "Mafia",
	[12] = "Anton Wolfe",
	[13] = "iaobardar",
	[14] = "Rubikow",
	[15] = "PPAN",
	[16] = "YuLun",
	[17] = "ONSVRG",
	[18] = "Larry Walsh",
	[19] = "CoolJWB",




}